# Generated by Django 4.2.6 on 2023-11-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0008_actionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='addcash',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
