# Generated by Django 4.2.6 on 2023-11-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0019_replacementitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='sale_cash',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
