# Generated by Django 4.2.6 on 2023-11-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0020_actionhistory_sale_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=51, max_digits=10),
            preserve_default=False,
        ),
    ]
