# Generated by Django 4.2.6 on 2023-11-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0025_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostOfGoodsSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.stock')),
            ],
        ),
    ]
