# Generated by Django 4.2.6 on 2023-11-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0030_sale_batch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='batch_number',
        ),
    ]
