# Generated by Django 4.2.6 on 2023-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0032_defectiveitem_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
