# Generated by Django 4.2.6 on 2023-11-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0037_stockreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='COG',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
