# Generated by Django 4.2.6 on 2023-11-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0038_actionhistory_cog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionhistory',
            name='COG',
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.itemsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.itemsmodel')),
            ],
        ),
    ]
