# Generated by Django 4.2.6 on 2023-11-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0039_remove_actionhistory_cog_salesreturn_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='batch_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.stock'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='batch_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.stock'),
        ),
    ]
