# Generated by Django 4.2.6 on 2023-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0042_remove_salesreturn_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_adjust',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
