# Generated by Django 4.2.6 on 2023-11-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0046_cogsmodel_delete_profitinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cogsmodel',
            name='cogs_sum',
            field=models.IntegerField(),
        ),
    ]
