# Generated by Django 4.2.6 on 2023-11-30 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0049_ownerequity'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsmodel',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Itemsmodel', to='stockmgmt.category'),
            preserve_default=False,
        ),
    ]
