# Generated by Django 4.2.6 on 2023-12-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0050_itemsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsmodel',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category'),
        ),
    ]
