# Generated by Django 4.2.6 on 2023-12-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0053_remove_person_city_remove_person_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsmodel',
            name='Category',
        ),
    ]
