# Generated by Django 4.2.6 on 2023-10-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='rate',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
