# Generated by Django 4.2.6 on 2023-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0012_alter_actionhistory_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionhistory',
            name='cash',
        ),
        migrations.AddField(
            model_name='sale',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
