# Generated by Django 4.2.6 on 2023-11-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0014_actionhistory_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
