# Generated by Django 4.2.6 on 2023-11-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0015_itemsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.itemsmodel'),
            preserve_default=False,
        ),
    ]
