# Generated by Django 4.2.6 on 2023-11-08 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0016_alter_stock_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectiveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.itemsmodel')),
            ],
        ),
    ]
