# Generated by Django 4.2.6 on 2023-11-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0021_actionhistory_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionhistory',
            name='total_value',
        ),
    ]
