# Generated by Django 4.2.6 on 2023-11-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0024_alter_stock_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('Exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.expense')),
            ],
        ),
    ]
