# Generated by Django 4.2.6 on 2023-11-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0026_costofgoodssold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costofgoodssold',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='costofgoodssold',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='costofgoodssold',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='costofgoodssold',
            name='item_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.itemsmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costofgoodssold',
            name='stock_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costofgoodssold',
            name='total_values',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
