# Generated by Django 4.2.6 on 2023-11-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0028_stock_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batch_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
