# Generated by Django 4.2.6 on 2023-11-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0034_stock_account_payable_stock_account_recieveable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='account_recieveable',
        ),
        migrations.AddField(
            model_name='sale',
            name='account_recieveable',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
