# Generated by Django 4.2.6 on 2023-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0040_alter_replacement_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='sub_cash',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='action',
            field=models.CharField(choices=[('defective', 'Defective'), ('replace', 'Replace'), ('no_action', 'No action')], default='no_action', max_length=10),
        ),
    ]
