# Generated by Django 4.2.6 on 2023-11-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0041_replacement_sub_cash_alter_salesreturn_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='category',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='item_name',
        ),
        migrations.DeleteModel(
            name='Replacement',
        ),
        migrations.DeleteModel(
            name='SalesReturn',
        ),
    ]
