# Generated by Django 4.2.6 on 2023-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0044_remove_sale_cash_adjust'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COGS_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
