# Generated by Django 4.2.6 on 2023-11-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0047_alter_cogsmodel_cogs_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cogsmodel',
            name='cogs_sum',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
