# Generated by Django 4.2.6 on 2023-11-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0048_alter_cogsmodel_cogs_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerEquity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.IntegerField()),
            ],
        ),
    ]
