# Generated by Django 4.2.6 on 2023-12-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0061_itemsmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsmodel',
            name='category',
        ),
    ]
