# Generated by Django 4.2.6 on 2023-12-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0063_itemsmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cogsmodel',
            name='cogs_sum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
