# Generated by Django 4.2.6 on 2023-12-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0064_alter_cogsmodel_cogs_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales_values', models.IntegerField(default=0)),
            ],
        ),
    ]
