# Generated by Django 4.2.6 on 2023-12-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0065_salesvalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesValues',
        ),
    ]
